language: r
sudo: required
cache: packages
dist: trusty
r: release
r_binary_packages:
    - covr
    - roxygen
    - lintr
r_github_packages:
    - MangoTheCat/rcmdcheck
script:
  - R -e 'r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); l <- lintr::lint_package("."); print(l); quit(save = "no", status = if (length(c(r$errors, r$warnings, l)) > 1 || grepl("FAILED", r$output$stdout)) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - R -e 'library(covr);coveralls()'
env:
  - global:
    - CI=TRUE
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - LINTR_COMMENT_BOT=false
